"""added name column un department, added delegation table

Revision ID: 0d377d363154
Revises: cb5744a6095b
Create Date: 2025-04-16 17:25:19.794381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0d377d363154'
down_revision = 'cb5744a6095b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('department', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_submitted', sa.Date(), nullable=True))
        batch_op.alter_column('student_last_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_first_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_uh_id',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_program_plan',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_academic_career',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_mailing_address',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_city',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_state',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_zip_code',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('student_email',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.drop_constraint('FK__general_p__user___251C81ED', type_='foreignkey')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_finalized')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finalized', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__general_p__user___251C81ED', 'user', ['user_id'], ['id'])
        batch_op.alter_column('student_email',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_zip_code',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_state',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_city',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_mailing_address',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_academic_career',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_program_plan',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_uh_id',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_first_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('student_last_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.drop_column('date_submitted')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
