"""added is finalized to CA responses

Revision ID: 10ca9560196a
Revises: 987b3b8d79ea
Create Date: 2025-04-21 18:57:22.024419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ca9560196a'
down_revision = '987b3b8d79ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_responses', schema=None) as batch_op:
        batch_op.drop_column('is_finalized')

    # ### end Alembic commands ###
