"""made gen pet form fields nullable

Revision ID: 1d2157266c6f
Revises: 946a5db74879
Create Date: 2025-04-16 17:15:42.034502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2157266c6f'
down_revision = '946a5db74879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delegation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegation',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name='FK__delegatio__from___2EA5EC27'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name='FK__delegatio__to_us__2F9A1060'),
    sa.PrimaryKeyConstraint('id', name='PK__delegati__3213E83F08D3BB25')
    )
    # ### end Alembic commands ###
