"""updated Delegation table

Revision ID: 3047012a28c3
Revises: 2f6fb5f0a049
Create Date: 2025-04-21 16:23:32.749469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3047012a28c3'
down_revision = '2f6fb5f0a049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_child_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dept_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('FK__delegatio__from___41B8C09B', type_='foreignkey')
        batch_op.drop_constraint('FK__delegatio__to_us__42ACE4D4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['to_child_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['dept_to'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['from_parent_id'], ['id'])
        batch_op.drop_column('from_user_id')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('to_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__delegatio__to_us__42ACE4D4', 'user', ['to_user_id'], ['id'])
        batch_op.create_foreign_key('FK__delegatio__from___41B8C09B', 'user', ['from_user_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('dept_to')
        batch_op.drop_column('to_child_id')
        batch_op.drop_column('from_parent_id')

    # ### end Alembic commands ###
