"""updated Delegation table

Revision ID: 33a5fb03d9c6
Revises: 3047012a28c3
Create Date: 2025-04-21 16:27:58.298018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a5fb03d9c6'
down_revision = '3047012a28c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_from', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department', ['dept_from'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dept_from')

    # ### end Alembic commands ###
