"""removed extra table keys for TW

Revision ID: 4b860a51e15c
Revises: d821e48c2938
Create Date: 2025-03-18 22:26:24.700462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b860a51e15c'
down_revision = 'd821e48c2938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.drop_column('financial_aid_signature')
        batch_op.drop_column('isss_signature')
        batch_op.drop_column('financial_aid_date')
        batch_op.drop_column('veterans_date')
        batch_op.drop_column('advisor_signature')
        batch_op.drop_column('athletics_signature')
        batch_op.drop_column('athletics_date')
        batch_op.drop_column('isss_date')
        batch_op.drop_column('advisor_name')
        batch_op.drop_column('veterans_signature')
        batch_op.drop_column('advisor_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advisor_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('veterans_signature', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('advisor_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isss_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('athletics_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('athletics_signature', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('advisor_signature', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('veterans_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('financial_aid_date', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isss_signature', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('financial_aid_signature', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
