"""added is finalized and last updated to general petition

Revision ID: 5933c390080b
Revises: 76d91907aae5
Create Date: 2025-04-16 15:24:34.351026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5933c390080b'
down_revision = '0d377d363154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_submitted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_submitted', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('is_finalized')

    # ### end Alembic commands ###
