"""Updated Request and ApprovalProcess models

Revision ID: 6af0db188036
Revises: 886c963141bc
Create Date: 2025-03-17 22:32:26.166058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af0db188036'
down_revision = '886c963141bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('FK_student', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('semester')
        batch_op.drop_column('student_email')
        batch_op.drop_column('details')
        batch_op.drop_column('year')
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('details', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_student', 'user', ['student_email'], ['email'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
