"""Fix approver relationship in ApprovalProcess

Revision ID: 8332cb8b574a
Revises: 78c1a717842e
Create Date: 2025-03-18 10:08:33.823969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8332cb8b574a'
down_revision = '78c1a717842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('request_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.drop_constraint('FK__request__student__4D5F7D71', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_email'], ['email'])
        batch_op.drop_column('student_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__request__student__4D5F7D71', 'user', ['student_id'], ['id'])
        batch_op.drop_column('details')
        batch_op.drop_column('year')
        batch_op.drop_column('semester')
        batch_op.drop_column('request_type')
        batch_op.drop_column('student_email')

    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.alter_column('approver_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
