"""Added updated_at to User model

Revision ID: 886c963141bc
Revises: 2d38b37c4818
Create Date: 2025-03-07 10:16:03.505094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886c963141bc'
down_revision = '2d38b37c4818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
