"""clean migration

Revision ID: 987b3b8d79ea
Revises: b5db913f7361
Create Date: 2025-04-21 18:35:52.629049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987b3b8d79ea'
down_revision = 'b5db913f7361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
