"""added approval status to CA

Revision ID: a368dec6b45d
Revises: 95e96885aa59
Create Date: 2025-04-21 19:35:42.204502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a368dec6b45d'
down_revision = '95e96885aa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_responses', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
