"""Clean migration with valid req_id

Revision ID: b5db913f7361
Revises: 03a18224cf47
Create Date: 2025-04-21 18:16:07.871697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5db913f7361'
down_revision = '03a18224cf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('form_type', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['form_type'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=False))

    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=False))

    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('general_petition', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('approval_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('form_type')
        batch_op.drop_column('user_id')
        batch_op.drop_column('req_id')

    # ### end Alembic commands ###
