"""RCL response now stores email

Revision ID: d821e48c2938
Revises: eb6139c8f60e
Create Date: 2025-03-18 20:48:26.364408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd821e48c2938'
down_revision = 'eb6139c8f60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('year_last_digit',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.alter_column('year_last_digit',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
