"""Added phone, email, program, and academic_career to TWResponses

Revision ID: e9394d17cac0
Revises: 8332cb8b574a
Create Date: 2025-03-18 10:42:32.814308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9394d17cac0'
down_revision = '8332cb8b574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('academic_career', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tw_responses', schema=None) as batch_op:
        batch_op.drop_column('academic_career')
        batch_op.drop_column('program')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
