"""update RCL response table

Revision ID: eb6139c8f60e
Revises: e9394d17cac0
Create Date: 2025-03-18 12:18:42.307909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'eb6139c8f60e'
down_revision = 'e9394d17cac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_last_digit', sa.Text(), nullable=True))
        batch_op.drop_column('academic_difficulty')
        batch_op.drop_column('concurrent_proof_attached')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcl_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concurrent_proof_attached', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('academic_difficulty', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_column('year_last_digit')

    # ### end Alembic commands ###
